### ISSUE TITLE
Slow Loading Time Due to Large Hero Image

### ISSUE THREAD

**Issue by tnmy57** [Rahul-Sahani04/NoteSync#1]
I have noticed that the hero image on the project's website is significantly large, causing slow loading times. This issue can negatively impact the user experience and should be addressed to improve website performance.

**Comment by Rahul-Sahani04** [comment]
Thank you so much for bringing this to my attention! 🙌 I appreciate your keen eye for detail. I've tackled the oversized hero image issue, so now the website should load much faster, providing a smoother user experience. Your feedback is valuable, and if you ever spot anything else or have more suggestions, please don't hesitate to share. This effort makes the project even better! 😊🚀
